apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:Tql6Kee5w1rgA4jbPDJhuuXspHK42iw7,iv:hL5FpNS0dUhpA9I+v3Hobya5NF2sf+je85RrBBUTIXY=,tag:M5lfmZXSEFjUG0IJb37OSA==,type:str]
    admin-user: ENC[AES256_GCM,data:ppPnWLdMa+M=,iv:QZrOB4BUs8948TajoQovZUKHt2FmhT3KlM5g0/o71Uc=,tag:IvpjSiMyhmd9PzpbDF/9LA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yyj38ks5yu7fm95xach4ja0y45r8axcv2jypz3u7w5lrcxsgquyssx29rz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZkxLVkk1NUUzS3NUT3VW
            YnB0MXExdm5vMVp2SW1qZEZMR3BiMFBYczA0CjJ1SVNOMXd6ZTgwYnQ1RTZJRlBZ
            Wm1heXNUNHovZlFSNlFnU05oWW11a0EKLS0tIG1wbWZya1kzQXV4REQyckhSRlEy
            WmpxV1JMY0ZpVTN0Ykw3N2dzWGs3blEKkPZ5nVrAF5D0tV4VMrSqCWXxYkXM/ptY
            NJFv6kVNni/FFBM5AhoYcnQXmoInF/n1DHPXwKKACwmbmyj3rKOVWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-28T15:37:20Z"
    mac: ENC[AES256_GCM,data:EXE1VEOqCfzXaP/VX2zGiN56e3uQbbstpwfaTguWUNwEP+8u5hpIdDop/rsQFXQzwuK6t71XU0UL492R1sDKa2BcI3SZ/zqG8MQU3ikjO2U2T+XdwgfRHDjxDabyrQWuplVs8/3easOF72y8l/K6FjX1BilnvKxWKm7e8OhZtF4=,iv:Ym+VgukNHOgQP34u+72z2uAeN5xjAApOp6KfQAlFm38=,tag:FHeC7EipUGXE8BQQIdPIWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
